DROP TABLE IF EXISTS todo.users CASCADE;

CREATE TABLE todo.users (
	id int GENERATED BY default AS IDENTITY NOT NULL,
	login text NOT NULL,
	pass text NOT NULL,
	salt text NOT NULL,
	password_hint text NULL,
	name text NULL,
	email text NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp DEFAULT now() NOT NULL,
	active boolean DEFAULT true NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT user_login_unique UNIQUE (login)
);
CREATE INDEX idx_users_id ON todo.users(id);
CREATE INDEX idx_users_login ON todo.users(login);


DROP TABLE IF EXISTS todo.sessions;

CREATE TABLE todo.sessions (
    user_id int NOT NULL,
	access_token text NOT NULL,
	refresh_token text NOT NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	expire_access_at timestamp NOT NULL,
	expire_refresh_at timestamp NOT NULL,
	device text NULL,
	user_ip text NULL,
	CONSTRAINT sessions_access_unique UNIQUE (access_token),
	CONSTRAINT sessions_refresh_unique UNIQUE (refresh_token),
	CONSTRAINT sessions_users_fk FOREIGN KEY (user_id) REFERENCES todo.users(id) ON DELETE SET DEFAULT ON UPDATE SET DEFAULT
);
--CREATE unique INDEX sessions_access_idx ON todo.sessions USING btree (access_token);
--CREATE unique INDEX sessions_refresh_idx ON todo.sessions USING btree (refresh_token);
CREATE INDEX sessions_user_id_idx ON todo.sessions USING btree (user_id);
