CREATE TABLE todo.users (
	id int GENERATED BY default AS IDENTITY NOT NULL,
	login text NOT NULL,
	pass text NOT NULL,
	name text NULL,
	email text NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp DEFAULT now() NOT NULL,
	active boolean DEFAULT true NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT user_login_unique UNIQUE (login)
);
CREATE INDEX idx_users_id ON todo.users(id);
CREATE INDEX idx_users_login ON todo.users(login);
